### ISSUE TITLE
Group ID overflowed

### ISSUE THREAD

**Issue by godmoves** [brilee/MuGo#28]
When using mcts, the program crashed and returned `KeyError: -32768` in function ` _update_liberties group = self.groups[group_id]`. Is this a bug of code?

**Comment by godmoves** [comment]
```
def expand(self, move_probabilities):
    'Not check whether move reasonable'
    #self.children = {move: MCTSNode(self, move, prob)
    #    for move, prob in np.ndenumerate(move_probabilities)}
    self.children = {}
    for move, prob in np.ndenumerate(move_probabilities):
        if is_move_reasonable(self.position, move):
            self.children[move] = MCTSNode(self, move, prob)
    # Pass should always be an option! Say, for example, seki.
    self.children[None] = MCTSNode(self, None, 0)
```
It seems this part is wrong

**Comment by brilee** [comment]
I was too conservative with thinking how frequently group_id would increment. (if you have a chain that is group id = 17 and another chain group id 19, and you connect the two chains, then all stones of the new chain are assigned a new autoincrementing group_id. If you overflowed, then it implies that you're playing lots of random moves in your simulation.

Anyway, should be fixed by latest commit.
